acceso/urls.py
from django.urls import path
from . import views

app_name = 'acceso'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('mientras/', views.mientras, name = 'mientras'),
    
]

paraExamen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('deseos/', include('deseos.urls')),
    path('', include('acceso.urls')),
    path('admin/', admin.site.urls),
]

acceso/models.py
from django.db import models

class User(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=72)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# Create your models here.

acceso/forms.py
from django import forms
from acceso.models import *
import re

class UserForm(forms.ModelForm):
#validaciones:
    def clean_nombre(self):
        nombre = self.cleaned_data['nombre']
        if len(nombre) < 2:
            self.add_error('nombre', 'El nombre debe contener más de 2 caracteres')
        return nombre
    
    def clean_apellido(self):
        apellido = self.cleaned_data['apellido']
        if len(apellido) < 2:
            self.add_error('apellido', 'El apellido debe contener más de 2 caracteres')
        return apellido
    
    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 8:
            self.add_error('password', 'El password debe contener más de 8 caracteres')
        return password
    
    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password') != cleaned_data.get('confirmar_password'):
            raise forms.ValidationError(
                'Las contraseñas no coinciden'
            )
    
    def clean_email(self):
        email = self.cleaned_data['email']
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(email):
            self.add_error('email', 'El patrón del email no es correcto')
        return email

#campos añadidos al formulario:

    password = forms.CharField(label = "password", max_length=72, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirmar_password = forms.CharField(label = "confirmar_password", max_length=72, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

#meta, fields, label, widget

    class Meta:
        model = User
        
        fields = ['nombre', 'apellido', 'email', 'password']
        
        labels = {
            'nombre' : 'Nombre: ',
            'apellido' : 'Apellido: ',
            'email' : 'Correo electrónico: ',
            'password' : 'Contraseña: ',
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class': 'form-control'}),
            'apellido' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'class': 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class': 'form-control'}),
        }

acceso/views.py
from django import forms
from django.shortcuts import render, HttpResponse, redirect
from acceso.forms import UserForm
from django.contrib import messages
from django.urls import reverse
import bcrypt
from acceso.models import User

class LoginForm(forms.Form):

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 8:
            self.add_error('password', 'El password debe contener más de 8 caracteres')
        return password

    email = forms.CharField(
        label = 'Email',
        required = True,
        widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder' : 'Correo electrónico'})
    )
    password = forms.CharField(
        label = 'Password',
        required = True,
        widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder' : 'Contraseña'})
    )

def index(request):
    if request.method == 'GET':
        context = {
        'formModel': UserForm(),
        'formLogin': LoginForm(),
        }
        return render(request, 'access/index.html', context)

    if request.method == 'POST':
        print(request.POST)
        form = UserForm(request.POST)
        if form.is_valid():
            #hasta aquí sólo se han aplicado las validaciones clean. La contraseña está en texto plano.
            usuario = form.save(commit=False)
            usuario.password = bcrypt.hashpw(usuario.password.encode(), bcrypt.gensalt()).decode()
            #Se hashea la contraseña
            usuario.save()
            #Se guarda el usuario con la contraseña hasheada.
            #Mensaje de éxito
            messages.success(request, 'Usuario registrado con éxito')
            return redirect(reverse('acceso:index'))
        else:
            messages.error(request, 'Con errores, solucionar')
            return render(request, 'access/index.html', {'formModel': form})

def login(request):
    if 'usuario' in request.session:
        messages.error(request, 'Ya estás logeado!')
        return redirect(reverse('acceso:index'))
    else:
        print(request.POST)
        form = LoginForm(request.POST)
        if form.is_valid(): #se valida la información que viene del form
            print(form.cleaned_data)
            #aquí en más viene la comprobación de las contraseñas.
            user = User.objects.filter(email=form.cleaned_data['email']).first() #se va a buscar la instancia de usario
            print(user)                                         #Arroja un queryset, por eso no será vacío. 
            if user: #aquí se comprueba si el usuario existe en el queryset user. 
                form_password = form.cleaned_data['password'] #se aloja el password que llegó del form
                print(form_password)
                print(user.password) #si viene en un queryset vamos a tener problemas para acceder.Poner first()
                if bcrypt.checkpw(form_password.encode(), user.password.encode()):
                    request.session['usuario'] = {'nombre' : user.nombre, 'email' : user.email, 'apellido' : user.apellido, 'id': user.id}
                    messages.success(request, 'Contraseñas coinciden!') #si concuerdan, se crea var sesion
                    return redirect(reverse('deseos:index'))
                else: 
                    messages.error(request, 'Contraseñas no coinciden')
            else:
                messages.error(request, 'Usuario no está regitrado en la base de datos')        
            
            return redirect('/')
        else:
            context = {
                'formModel' : UserForm(), #el form de registro se manda vacio.
                'formLogin' : form, #el form de login se manda con los datos para su arreglo
                }
            return render(request, 'access/index.html', context)

def logout(request):
    if 'usuario' in request.session:
        del request.session['usuario']
        return redirect(reverse('acceso:index'))

def mientras(request):
    return HttpResponse("hola desde nmientras")

acceso/templates/access/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock %}</title>
    {% load static %}	
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">  
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">User</a>  
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <span class="nav-link active text-info">Bienvenido, <b>{{request.session.usuario.nombre}}</b></span>
                    </li>
                </ul>
                    <a href="{% url 'acceso:logout' %}" class="btn btn-outline-danger">SALIR</a>
            </div>
            </div>
        </div>
    </nav>

    <div class="container">

    {% block contenido %}{% endblock %}

    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }
        
        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

acceso/templates/access/index.html
{% extends 'access/base.html' %}

{% block titulo %} Sesión {% endblock %}  

{% block contenido %}

<div class="row">
    <div class="col-6">
        <h3>Register</h3>
        <hr>
        <form action="" method="post">
            
            {% csrf_token %}
            {{ formModel.non_field_errors }}

            {% for field in formModel %}
            <div class="mb-3 row">

                <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                <div class="col-sm-9">
                    {{ field }}
                </div>

                {% if field.errors %}

                <div class="alert alert-danger mt-2" role="alert">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>

                {% endif %}

                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
            {% endfor %}

            <button class="btn btn-primary offset-2" type="submit">Enviar</button>
        </form>
    </div>

    <div class="col-6">
        <h3>Login</h3>
        <hr>
        <form action="{% url 'acceso:login' %}" method="post">
            
            {% csrf_token %}
            {{ formLogin.non_field_errors }}

            {% for field in formLogin %}
            <div class="mb-3 row">

                <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                <div class="col-sm-9">
                    {{ field }}
                </div>

                {% if field.errors %}

                <div class="alert alert-danger mt-2" role="alert">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>

                {% endif %}

                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
            {% endfor %}

            <button class="btn btn-primary offset-2" type="submit">Enviar</button>
        </form>

{% endblock %}